AWSTemplateFormatVersion: '2010-09-09'
Description: S3 bucket using parameters

Parameters:
  S3BucketName:
    Description: Name of the S3 bucket
    Type: String
    MinLength: 3
    MaxLength: 63
    # AllowedPattern: "^[A-Za-z0-9.-]*$"
    # ConstraintDescription: "Must be an alphanumeric string with dots or hyphens"


Resources:
  abucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3BucketName
